import re
import json

# Mapeamento oficial dos 64 Hexagramas clássicos
TITULOS_HEXAGRAMAS = {
    1: ("Ch'ien", "O Criativo", "Céu sobre Céu", "☰ / ☰"),
    2: ("K'un", "O Receptivo", "Terra sobre Terra", "☷ / ☷"),
    3: ("Chun", "A Dificuldade Inicial", "Água sobre Trovão", "☵ / ☳"),
    4: ("Meng", "A Inexperiência Juvenil", "Montanha sobre Água", "☶ / ☵"),
    5: ("Hsü", "A Espera (Nutrição)", "Água sobre Céu", "☵ / ☰"),
    6: ("Sung", "O Conflito", "Céu sobre Água", "☰ / ☵"),
    7: ("Shih", "O Exército (Disciplina)", "Terra sobre Água", "☷ / ☵"),
    8: ("Pi", "A União (Solidariedade)", "Água sobre Terra", "☵ / ☷"),
    9: ("Hsiao Ch'u", "O Poder de Domar do Pequeno", "Vento sobre Céu", "☴ / ☰"),
    10: ("Lü", "A Conduta (Pisar)", "Céu sobre Lago", "☰ / ☱"),
    11: ("T'ai", "A Paz (Harmonia)", "Terra sobre Céu", "☷ / ☰"),
    12: ("P'i", "A Estagnação (O Bloqueio)", "Céu sobre Terra", "☰ / ☷"),
    13: ("T'ung Jên", "A Comunhão entre os Homens", "Céu sobre Fogo", "☰ / ☲"),
    14: ("Ta Yu", "A Posse em Grande Medida", "Fogo sobre Céu", "☲ / ☰"),
    15: ("Ch'ien", "A Modéstia", "Terra sobre Montanha", "☷ / ☶"),
    16: ("Yü", "O Entusiasmo", "Trovão sobre Terra", "☳ / ☷"),
    17: ("Sui", "A Perseguição / O Seguimento", "Lago sobre Trovão", "☱ / ☳"),
    18: ("Ku", "Trabalho no Que Se Deteriorou", "Montanha sobre Vento", "☶ / ☴"),
    19: ("Lin", "A Aproximação", "Terra sobre Lago", "☷ / ☱"),
    20: ("Kuan", "A Contemplação (A Visão)", "Vento sobre Terra", "☴ / ☷"),
    21: ("Shih Ho", "Morder e Romper", "Fogo sobre Trovão", "☲ / ☳"),
    22: ("Pi", "A Graça (A Beleza)", "Montanha sobre Fogo", "☶ / ☲"),
    23: ("Po", "A Desagregação (A Ruína)", "Montanha sobre Terra", "☶ / ☷"),
    24: ("Fu", "O Retorno (O Ponto de Virada)", "Terra sobre Trovão", "☷ / ☳"),
    25: ("Wu Wang", "A Inocência (O Inesperado)", "Céu sobre Trovão", "☰ / ☳"),
    26: ("Ta Ch'u", "O Grande Poder de Domar", "Montanha sobre Céu", "☶ / ☰"),
    27: ("I", "A Provisão de Alimentos (As Mandíbulas)", "Montanha sobre Trovão", "☶ / ☳"),
    28: ("Ta Kuo", "Preponderância do Grande", "Lago sobre Vento", "☱ / ☴"),
    29: ("K'an", "O Abismo (A Água)", "Água sobre Água", "☵ / ☵"),
    30: ("Li", "O Aderir (O Fogo)", "Fogo sobre Fogo", "☲ / ☲"),
    31: ("Hsien", "A Influência (O Atendimento)", "Lago sobre Montanha", "☱ / ☶"),
    32: ("Hêng", "A Constância (A Duração)", "Trovão sobre Vento", "☳ / ☴"),
    33: ("TUN", "A Retirada (O Recuo)", "Céu sobre Montanha", "☰ / ☶"),
    34: ("Ta Chuang", "O Poder do Grande", "Trovão sobre Céu", "☳ / ☰"),
    35: ("Chin", "O Progresso", "Fogo sobre Terra", "☲ / ☷"),
    36: ("Ming I", "O Obscurecimento da Luz", "Terra sobre Fogo", "☷ / ☲"),
    37: ("Chia Jên", "A Família", "Vento sobre Fogo", "☴ / ☲"),
    38: ("K'uei", "A Oposição", "Fogo sobre Lago", "☲ / ☱"),
    39: ("Chien", "O Obstáculo", "Água sobre Montanha", "☵ / ☶"),
    40: ("Hsieh", "A Liberação", "Trovão sobre Água", "☳ / ☵"),
    41: ("Sun", "A Diminuição", "Montanha sobre Lago", "☶ / ☱"),
    42: ("I", "O Aumento", "Vento sobre Trovão", "☴ / ☳"),
    43: ("Kua", "A Irrupção (A Resolução)", "Lago sobre Céu", "☱ / ☰"),
    44: ("Kou", "Vindo ao Encontro", "Céu sobre Vento", "☰ / ☴"),
    45: ("Ts'ui", "A Reunião (A Coleção)", "Lago sobre Terra", "☱ / ☷"),
    46: ("Shêng", "A Elevação (O Empurrar para Cima)", "Terra sobre Vento", "☷ / ☴"),
    47: ("K'un", "A Opressão (A Exaustão)", "Lago sobre Água", "☱ / ☵"),
    48: ("Ching", "O Poço de Água", "Água sobre Vento", "☵ / ☴"),
    49: ("Ko", "A Revolução (A Mudar de Pele)", "Lago sobre Fogo", "☱ / ☲"),
    50: ("Ting", "O Caldeirão", "Fogo sobre Vento", "☲ / ☴"),
    51: ("Chên", "O Trovão (A Aposta)", "Trovão sobre Trovão", "☳ / ☳"),
    52: ("Kên", "A Montanha (O Aquietamento)", "Montanha sobre Montanha", "☶ / ☶"),
    53: ("Chien", "O Desenvolvimento Gradual", "Vento sobre Montanha", "☴ / ☶"),
    54: ("Kuei Mei", "A Jovem que se Casa", "Trovão sobre Lago", "☳ / ☱"),
    55: ("Fêng", "A Abundância (A Plenitude)", "Trovão sobre Fogo", "☳ / ☲"),
    56: ("Lü", "O Viajante", "Fogo sobre Montanha", "☲ / ☶"),
    57: ("Sun", "O Suave (O Vento)", "Vento sobre Vento", "☴ / ☴"),
    58: ("Tui", "O Alegre (O Lago)", "Lago sobre Lago", "☱ / ☱"),
    59: ("Huan", "A Dissolução (A Dispersão)", "Vento sobre Água", "☴ / ☵"),
    60: ("Chieh", "A Limitação", "Água sobre Lago", "☵ / ☱"),
    61: ("Chung Fu", "A Verdade Interior", "Vento sobre Lago", "☴ / ☱"),
    62: ("Hsiao Kuo", "Preponderância do Pequeno", "Trovão sobre Montanha", "☳ / ☶"),
    63: ("Chi Chi", "Após a Conclusão", "Água sobre Fogo", "☵ / ☲"),
    64: ("Wei Chi", "Antes da Conclusão", "Fogo sobre Água", "☲ / ☵")
}

# Gerador autoral refinado baseado em Wilhelm e Cleary
def gerar_hexagrama(num):
    nome_pinyin, nome_pt, trigrama_nome, trigrama_simbolo = TITULOS_HEXAGRAMAS[num]
    
    # Textos originais e autorais com tom terapêutico e analítico
    sinteses = {
        1: "Energia primordial em expansão máxima. Clareza de propósito, iniciativa e poder criativo focado.",
        2: "Sustentação silenciosa, escuta profunda e receptividade ativa antes da ação.",
        3: "Gestação sob fricção inicial. A turbulência do começo exige organização e firmeza sem desespero.",
        4: "Cultivo do aprendizado com humildade intelectual. Momento de buscar orientação qualificada.",
        5: "Paciência estratégica e gestação. Nutrir as forças internas enquanto a oportunidade amadurece.",
        6: "Recuo diplomático frente ao atrito. Preservação de vitalidade evitando confrontos estéreis.",
        7: "Organização rigorosa, autodisciplina e alinhamento de foco para superar grandes desafios.",
        8: "Fortalecimento de alianças autênticas e sentimento de pertencimento com valores alinhados.",
        9: "Pequenos ajustes diários e persuasão sutil. A constância suave vence a resistência bruta.",
        10: "Conduta impecável e compostura em terrenos delicados. Transitar com respeito e segurança.",
        11: "Fluidez, prosperidade e alinhamento. Momento excelente para consolidar conquistas de longo prazo.",
        12: "Estagnação externa e recolhimento estratégico. Proteger valores e economizar energia.",
        13: "União em torno de causas elevadas. Comunhão transparente e colaboração de alto nível.",
        14: "Abundância e clareza de recursos. Exercer a prosperidade com responsabilidade e generosidade.",
        15: "Modéstia genuína que equilibra o excesso. A simplicidade sustenta a verdadeira autoridade.",
        16: "Entusiasmo contagiante e motivação alinhada a um planejamento realista e disciplinado.",
        17: "Adaptabilidade inteligente ao ritmo dos acontecimentos. Saber seguir para depois liderar.",
        18: "Saneamento de velhos padrões e reparação de falhas estruturais com coragem analítica.",
        19: "Aproximação promissora e expansão. Aproveitar o momento favorável para agir com determinação.",
        20: "Contemplação reflexiva e visão panorâmica. Observar com profundidade antes de decidir.",
        21: "Romper obstáculos e impor limites necessários. Decisão firme contra o que impede o avanço.",
        22: "Graça estática e elegância visual, sem esquecer de nutrir a essência substancial interna.",
        23: "Desagregação do que é desnecessário. Permitir a queda do ilusório para preservar a estrutura essencial.",
        24: "Ponto de virada e renovação de vitalidade. O retorno da luz e da motivação após o recolhimento.",
        25: "Ação espontânea alinhada à verdade natural. Agir com integridade sem segundas intenções tóxicas.",
        26: "Acúmulo de sabedoria e autocontrole firme. Conter a força para aplicá-la no momento exato.",
        27: "Nutrição consciente do corpo e da mente. Cuidar daquilo que se consome e do que se expressa.",
        28: "Carga pesada sobre a estrutura. Momento crítico que exige reforço imediato e alivio de peso.",
        29: "Travessia do abismo através da constância e coragem interior. Manter a serenidade na incerteza.",
        30: "Clareza de consciência e adesão a princípios elevados. Iluminar a percepção com lucidez.",
        31: "Ressonância mútua e atração genuína. Comunicação intuitiva e abertura emocional.",
        32: "Constância, resistência e ritmo sustentável. Manter a fidelidade aos propósitos de longo prazo.",
        33: "Retirada tática consciente. Recuar com elegância para preservar a soberania e o comando.",
        34: "Grande poder em mãos que exige contenção responsável. Evitar o uso impulsivo da força.",
        35: "Progresso visível e reconhecimento merecido. Avançar com confiança e transparência.",
        36: "Preservação da luz interna em tempos de incompreensão. Manter a integridade de forma discreta.",
        37: "Fortalecimento das bases internas e clareza de papéis dentro da estrutura familiar e de equipe.",
        38: "Divergência de perspectivas. Encontrar pontos de convergência sem anular as individualidades.",
        39: "Superação de obstáculos pela reavaliação de rotas. Buscar apoio e contornar a montanha.",
        40: "Alívio imediato de tensões e desatamento de nós. Momento de perdoar o passado e avançar.",
        41: "Simplificação voluntária e redução do supérfluo para fortalecer o essencial e recuperar o foco.",
        42: "Expansão, ganho e generosidade. Momento de investir no crescimento e apoiar os demais.",
        43: "Resolução firme e corte definitivo com padrões nocivos. Comunicar decisões com clareza.",
        44: "Encontro com forças sutis que exigem cautela. Não se deixar dominar por influências impulsivas.",
        45: "Reunião de forças e concentração de propósitos. Criar coesão e proteção para o grupo.",
        46: "Elevação gradual e consistente. Subir passo a passo com esforço contínuo e fundamentado.",
        47: "Exaustão temporária e sensação de confinamento. Buscar a força interna na serenidade mental.",
        48: "Acesso à fonte inesgotável de sabedoria interna. Manter os canais de autoconhecimento limpos.",
        49: "Renovação profunda, mudança de pele e transformação de velhas estruturas obsoletas.",
        50: "Alquimia interna e refinamento de caráter. Transformação de matérias brutas em sabedoria.",
        51: "Despertar súbito através do impacto. O choque inicial que convida à reorganização da vida.",
        52: "Aquietamento da mente e repouso da coluna. Encontrar a imobilidade serena no meio do turbilhão.",
        53: "Progresso gradual e orgânico. O crescimento sustentável que respeita os ritmos da natureza.",
        54: "Subordinação temporária e adaptação a papéis secundários com maturidade e discernimento.",
        55: "Plenitude e abundância no ápice. Desfrutar do momento com consciência da impermanência.",
        56: "Transitoriedade do viajante. Manter a flexibilidade e a modéstia em terras desconhecidas.",
        57: "Penetração suave como o vento. Influenciar e transformar através da persistência delicada.",
        58: "Alegria compartilhada, diálogo fluido e leveza nas trocas interpessoais.",
        59: "Dissolução de rigidez, preconceitos e barreiras emocionais. Retorno à fluidez natural.",
        60: "Limites saudáveis que estruturam a liberdade. Definir margens claras para evitar o transbordo.",
        61: "Verdade interior e empatia profunda. Conectar-se com o essencial no coração das relações.",
        62: "Atenção meticulosa aos detalhes pequenos. Moderação de expectativas em momentos delicados.",
        63: "Equilíbrio alcançado que exige vigilância. Manter a atenção para não relaxar o cuidado.",
        64: "Antes da conclusão total. Preparar o último passo com calma e foco para cruzar a linha."
    }

    analises = {
        1: "O Criativo representa a potência pura de realização. Quando este hexagrama é sorteado, o universo convida você a assumir a liderança de sua jornada com soberania e convicção. Contudo, o poder sem disciplina gera desgaste; alinhe sua visão analítica aos valores éticos.",
        2: "O Receptivo ensina que a verdadeira força muitas vezes reside na capacidade de acolher, escutar e sustentar. Antes de agir ou tomar uma decisão drástica, permita-se processar o cenário. A paciência receptiva constrói bases indestrutíveis.",
        3: "Toda grande transformação nasce de uma turbulência inicial. Não confunda a dificuldade do começo com sinal de fracasso. Organize seus recursos, estabeleça prioridades e siga em frente com firmeza serena.",
        4: "Reconhecer as próprias limitações é a maior prova de inteligência. Este é o momento ideal para buscar mentoria, estudar o terreno e aprender com quem já percorreu o caminho antes de você.",
        5: "A Espera não é passividade estéril, mas gestação consciente. Nutra sua mente e seu corpo com pensamentos elevados e práticas saudáveis enquanto as circunstâncias amadurecem externamente.",
        6: "Conflitos desgastam a vitalidade quando alimentados pelo ego. Avalie se vale a pena vencer uma discussão ao custo de sua paz interior. O recuo estratégico e o diálogo ponderado são marcas de maturidade.",
        7: "Grandes objetivos exigem autodisciplina de exército. Mantenha o foco em suas metas, estabeleça uma rotina clara e lidere sua vida com rigor amoroso e responsabilidade.",
        8: "Relações autênticas e alianças de valor sustentam o sucesso de longo prazo. Procure cultivar amizades e parcerias com pessoas que compartilham da sua busca por equilíbrio e evolução.",
        9: "Pequenos hábitos diários têm mais poder de transformação do que grandes impulsos isolados. Persista com suavidade e firmeza na direção correta.",
        10: "Navegar por ambientes exigentes ou lidar com pessoas complexas requer conduta impecável. Mantenha a elegância, a compostura e os limites éticos bem definidos.",
        11: "A Paz surge do alinhamento entre sua essência e suas ações. Aproveite este período de fluidez para investir na sua saúde física, mental e em projetos duradouros.",
        12: "Diante do bloqueio externo ou da estagnação, recolha-se. Projeta seu capital subjetivo e sua energia de influências tóxicas até que o ciclo de renovação se inicie.",
        13: "A comunhão com propósitos elevados multiplica os resultados. Una-se a grupos e projetos que promovam a integração, a ciência e o bem-estar coletivo.",
        14: "A abundância é um teste de responsabilidade. Administre suas conquistas com sabedoria, mantendo a modéstia e o desejo contínuo de contribuir para o mundo.",
        15: "A modéstia genuína eleva o indivíduo sem necessidade de autoafirmação. Quanto maior o seu conhecimento e sucesso, mais simples e acessível deve ser sua postura.",
        16: "O entusiasmo é o combustível da realização. Direcione essa energia com planejamento lógico e execução consistente para não se perder em mera empolgação passajaria.",
        17: "Saber se adaptar às mudanças do ambiente é a chave da sobrevivência emocional. Seja flexível como a água que contorna os obstáculos sem perder sua essência.",
        18: "Enfrente os velhos padrões comportamentais e traumas do passado com coragem analítica. Limpar as estruturas deterioradas abre espaço para um novo florescer.",
        19: "O momento é altamente favorável para avançar. Esteja presente, assuma responsabilidades e aproveite a maré de oportunidade com determinação.",
        20: "Apenas quem sabe parar e observar consegue enxergar além das aparências. Dedique tempo à introspecção e à análise panorâmica de sua vida.",
        21: "Há momentos em que se deve cortar o mal pela raiz. Imponha limites claros, tome decisões difíceis e rompa com hábitos que estejam drenando sua energia.",
        22: "Cultive a beleza interna e externa, mas lembre-se de que a estética deve refletir uma essência rica. Não se satisfaça com aparências superficiais.",
        23: "Permita que aquilo que já cumpriu seu papel se desfaça. A desagregação abre espaço para que a verdade essencial de sua vida se manifeste.",
        24: "Após a escuridão ou o esgotamento, surge a luz do renovo. Respeite os tempos de recuperação de seu organismo e celebre cada pequeno avanço.",
        25: "Agir com pureza de intenções atrai proteção natural. Mantenha a inocência do coração combinada com a discernimento da experiência.",
        26: "Acumule conhecimento, autocontrole e saúde. A verdadeira força é aquela que sabe o momento exato de ser aplicada com precisão.",
        27: "Aquilo com que você nutre sua mente e seu corpo determina sua saúde biológica e psíquica. Selecione seus pensamentos e alimentos com rigor.",
        28: "Quando a pressão externa ameaça dobrar suas forças, reduza o peso impositivo e busque suporte imediato. Preserve sua integridade física e emocional.",
        29: "Atravesse momentos de incerteza mantendo a fé em seus valores e a serenidade no coração. A água que flui pelo abismo eventualmente encontra o mar.",
        30: "A clareza de consciência ilumina o caminho mais sombrio. Mantenha-se fiel aos seus princípios éticos e à luz da razão equilibrada.",
        31: "A sensibilidade ao ambiente e a abertura ao diálogo geram encontros transformadores. Esteja atento às sincronicidades e sinais do corpo.",
        32: "A constância na prática diária de autocuidado constrói uma vida inabalável. Não busque resultados da noite para o dia; honre o processo.",
        33: "Recuar diante de forças avassaladoras não é covardia, mas inteligência tática. Preserve seu equilíbrio e sua dignidade em primeiro lugar.",
        34: "Poder sem autocontrole gera destruição. Use sua influência e conhecimento para construir e proteger, jamais para dominar impulsivamente.",
        35: "O progresso sustentável é fruto de dedicação e clareza. Avance com luz própria, sem precisar diminuir o brilho de ninguém ao seu redor.",
        36: "Em ambientes adversos, guarde seus tesouros internos em silêncio. A verdadeira luz brilha no interior sem necessidade de alarde público.",
        37: "Harmonize sua casa e suas relações mais próximas. A estabilidade no ambiente interno é a base para o sucesso no mundo externo.",
        38: "Aprenda a respeitar as diferenças de opinião sem transformar divergências em batalhas pessoais. Encontre o equilíbrio na diversidade.",
        39: "Diante de um obstáculo intransponível, pare e reavalie. Às vezes o caminho correto exige dar um passo ao lado ou pedir ajuda a especialistas.",
        40: "Liberte-se de ressentimentos e culpas do passado. O perdão e a descompressão emocional trazem uma sensação imediata de leveza e renovação.",
        41: "Elimine o excesso de compromissos e estímulos. A simplificação da rotina recupera o foco e devolve a vitalidade perdida no estresse.",
        42: "Compartilhe suas bênçãos e conhecimento. Quanto mais você contribui para o crescimento dos outros, mais o universo expande seu próprio caminho.",
        43: "Tome a decisão que vem adiando. A clareza de posicionamento afasta a ambiguidade e traz paz imediata ao sistema nervoso.",
        44: "Esteja atento a tentações de atalhos fáceis ou alianças duvidosas. Mantenha seus padrões de exigência e ética no nível mais elevado.",
        45: "Reúna suas forças em torno de um objetivo claro. A concentração de energia em uma única direção gera resultados extraordinários.",
        46: "Suba cada degrau com calma e persistência. O verdadeiro crescimento é aquele construído sobre fundações sólidas e graduais.",
        47: "Mesmo nas situações de limitação ou exaustão, lembre-se de que a mente pode permanecer livre. Busque o refúgio na meditação e no autocuidado.",
        48: "Beba da fonte inacabável da sabedoria interna. O conhecimento acumulado pela experiência é o seu recurso mais valioso.",
        49: "Não tenha medo de mudar de opinião ou reinventar sua rotina. A renovação de hábitos é indispensável para a manutenção da longevidade.",
        50: "Refine seus pensamentos e sentimentos como o metal no fogo. A alquimia da transformação pessoal transforma crises em sabedoria de vida.",
        51: "Os imprevistos da vida servem para despertar nossa consciência. Receba os choques do destino como convites para um reajuste de rota.",
        52: "Aprenda a arte de silenciar o corpo e acalmar a mente. O aquietamento diário é a vacina definitiva contra o estresse corporativo.",
        53: "Respeite o tempo de maturação de seus projetos e relacionamentos. O avanço gradual e constante garante raízes profundas e frutos doces.",
        54: "Aceite as fases temporárias de transição com graciosidade. Nem sempre estamos no controle total; saiba fluir com o momento.",
        55: "Desfrute da plenitude de suas conquistas com gratidão. Mantenha os pés no chão, sabendo que a vida é feita de ciclos de expansão e recolhimento.",
        56: "Mantenha a mente aberta e o coração humilde em novas experiências. A postura de constante aprendiz enriquece a alma.",
        57: "A persistência suave do vento molda até as rochas mais duras. Cultive a paciência amorosa no tratamento de seus desafios.",
        58: "Cultive a alegria sincera nas coisas simples e na convivência harmônica. A leveza de espírito atrai saúde e relacionamentos prósperos.",
        59: "Dissolva os bloqueios mentais e rigidezes emocionais. Permita que a compaixão e o entendimento fluam livremente em sua rotina.",
        60: "Defina limites saudáveis para seu trabalho, descanso e alimentação. As margens claras trazem segurança e liberdade real para a vida.",
        61: "A verdade e a sinceridade conectam você ao coração dos outros. Seja autêntico em suas palavras e transparente em suas intenções.",
        62: "Cuide das pequenas coisas com imenso carinho. A excelência nos detalhes constrói a grandeza dos grandes resultados.",
        63: "Mesmo quando tudo parecer resolvido, mantenha a atenção preventiva. O cuidado contínuo preserva o equilíbrio conquistado.",
        64: "Esteja atento aos momentos finais de transição. Mantenha o foco até cruzar completamente a linha de chegada de seus objetivos."
    }

    alertas = {
        1: "Energia simpática em alta expansão. Atenção à hiperativação corporal, tensão na região cervical, mandíbula rígida e impulso de aceleração constante.",
        2: "Necessidade de estímulo ao tônus vagal ventral. Excelente momento para desacelerar o ritmo respiratório, soltar o abdômen e permitir repouso regenerativo.",
        3: "Ansiedade antecipatória e sensação de sobrecarga nos ombros. Lembre-se de que o corpo precisa de pausas rítmicas para digerir mudanças.",
        4: "Sensação de névoa mental (brain fog) por excesso de estímulos dispersos. Pratique a desaceleração visual e foco único.",
        5: "Inquietação motora e respiração curta. Recupere o ritmo respiratório diafragmático para ancorar a presença no aqui e agora.",
        6: "Rigidez no plexo solar e contração diafragmática. Libere a tensão acumulada no peito através de expirações prolongadas.",
        7: "Tensão muscular nas costas e postura defensiva. Promova o alinhamento postural sem rigidez excessiva.",
        8: "Abertura do centro cardíaco e redução da carga alostática através da conexão humana autêntica.",
        9: "Tensão nos micro-músculos faciais e olhos cansados por hiperfoco. Faça pausas para descanso visual.",
        10: "Estado de vigília simpática sustentada. Cultive o enraizamento através dos pés tocando firmemente o chão.",
        11: "Sensação de leveza no peito e tom vagal ventral plenamente ativo. Momento ideal para integrar novos hábitos de saúde.",
        12: "Sensação de peso corporal e tendência à apatia/congelamento (vagal dorsal). Estimule o corpo com caminhadas suaves e hidratação.",
        13: "Descompressão torácica e expansão da capacidade vital respiratória. Ótimo momento para práticas de grupo.",
        14: "Sensação de vigor metabólico. Cuidado com o excesso de consumo energético e estresse térmico.",
        15: "Descontração muscular profunda e alívio da sobrecarga articular nos ombros e trapézio.",
        16: "Aceleração dos batimentos cardíacos por excitação. Pratique a respiração ritmada 4-7-8 para manter o centro.",
        17: "Soltura da articulação temporomandibular (ATM) e flexibilidade da coluna vertebral.",
        18: "Necessidade de detox somático. Elimine toxinas com hidratação abundante e massagem nos pontos meridianos.",
        19: "Estímulo positivo da circulação sanguínea. Aproveite para realizar atividades físicas moderadas ao ar livre.",
        20: "Desaceleração do ritmo cardíaco e relaxamento do sistema nervoso central através do silêncio consciente.",
        21: "Tensão acumulada na mandíbula e dentes travados (bruxismo). Realize auto-massagem na musculatura do masseter.",
        22: "Suavização do tom de voz e relaxamento dos músculos da garganta e pescoço.",
        23: "Sensação de esgotamento de energia e fadiga muscular. Permita-se dormir horas adicionais de sono profundo.",
        24: "Sensação de formigamento restaurador nos membros. O sistema nervoso está reconectando sua vitalidade.",
        25: "Alívio da ansiedade por soltura da necessidade de controle. Solte a região pélvica e lombar.",
        26: "Retenção de energia na região do abdômen superior. Realize respirações profundas para massagear as vísceras.",
        27: "Atenção ao sistema digestivo. Evite comer sob estado de estresse ou correria corporativa.",
        28: "Sobrecarga na região lombar por carregamento de peso emocional ou físico. Faça alongamentos leves da cadeia posterior.",
        29: "Hipervigilância dos sentidos. Pratique o fechamento de olhos por 5 minutos ao longo do dia laboral.",
        30: "Calor na região da cabeça e olhos secos. Beba água e aplique compressas mornas para aliviar a tensão ocular.",
        31: "Sensibilidade tátil aumentada e facilidade de relaxamento através do toque terapêutico.",
        32: "Estabilização do ritmo cardíaco (VFC). O corpo responde com resiliência e resistência física duradoura.",
        33: "Alívio imediato da pressão nas têmporas ao afastar-se do fator estressante. Priorize o descanso isolado.",
        34: "Sensação de excesso de calor corporal. Equilibre o organismo com banhos frios e alimentação leve.",
        35: "Expansão da postura e abertura dos ombros. O corpo expressa confiança e vitalidade natural.",
        36: "Tensão sutil na garganta por engolir sentimentos não ditos. Pratique a expressão criativa ou escrita terapêutica.",
        37: "Sensação de aconchego térmico e equilíbrio do sistema imunológico através do ambiente acolhedor.",
        38: "Desconforto digestivo episódico por irritabilidade. Cuide do nervo vago através de gargarejos e respiração lenta.",
        39: "Sensação de travamento nos joelhos e tornozelos. Faça pausas para movimentar as articulações dos pés.",
        40: "Soltura imediata do diafragma e sensação de oxigenação abundante no cérebro.",
        41: "Leveza digestiva e eliminação de inchaços corporais através da simplificação alimentar.",
        42: "Aumento da vitalidade geral e sensação de calor agradável nas palmas das mãos e solas dos pés.",
        43: "Descarregamento de tensão retida nas mãos e braços. Sacuda os membros para liberar o excesso de adrenalina.",
        44: "Atenção a impulsos compulsivos ou picos de ansiedade repentinos. Respire fundo 3 vezes antes de reagir.",
        45: "Fortalecimento do tônus muscular global e sensação de enraizamento no solo.",
        46: "Melhora gradual na resistência aeróbica e disposição física ao acordar.",
        47: "Nível baixo de energia vital (qi/prana). Evite treinos exaustivos e priorize o descanso passivo.",
        48: "Equilíbrio dos fluidos corporais e bom funcionamento dos rins. Mantenha a hidratação constante.",
        49: "Desprendimento de tensões crônicas antigas na fáscia muscular. Faça sessões de liberação miofascial.",
        50: "Harmonização do eixo cérebro-intestino. Sentimento de centro e ancoragem corporal.",
        51: "Resposta de sobressalto (startle reflex) ativada. Acalme o sistema nervoso com toques firmes no peito.",
        52: "Desativação completa da resposta de luta ou fuga. Estado ideal de meditação e repouso celular.",
        53: "Ritmo metabólico estável e sustentado. O corpo se regenera sem picos de estresse.",
        54: "Tensão na região dos ombros por tentar se adaptar a expectativas alheias. Solte os ombros consciente mente.",
        55: "Sensação de abundância energética. Cuidado para não esgotar as reservas no final do dia.",
        56: "Adaptação rápida a mudanças de temperatura e ambiente. Mantenha o corpo protegido e agasalhado.",
        57: "Relaxamento da musculatura profunda ao redor da coluna vertebral por respiração contínua.",
        58: "Sorriso espontâneo e desativação das rugas de expressão. Estímulo das hormônios do bem-estar.",
        59: "Liberação de retenção hídrica e alívio do peso nas pernas através de drenagem simples.",
        60: "Regularidade nos ritmos biológicos (sono, vigília e digestão). O corpo agradece a rotina clara.",
        61: "Sensação de paz no centro do peito. Diminuição expressiva da frequência cardíaca em repouso.",
        62: "Redução de tremores ou inquietação nas mãos através da focagem em tarefas manuais sutis.",
        63: "Homeostase alcançada. Mantenha os cuidados básicos sem descuidar da prevenção diária.",
        64: "Sensação de expectativa e prontidão. Mantenha a respiração baixa no abdômen para evitar a ansiedade final."
    }

    return {
        "numero": num,
        "nome": f"{nome_pinyin} / {nome_pt}",
        "trigramas": f"{trigrama_nome} ({trigrama_simbolo})",
        "imagem": f"A imagem clássica de {nome_pt} orienta a busca por clareza moral, sabedoria de decisão e integridade de vida.",
        "julgamento": f"A orientação para {nome_pt} indica o momento certo para alinhar intenções e colher os frutos da perseverança ética.",
        "sintese": sinteses[num],
        "analiseCompleta": analises[num],
        "alertaSomatico": alertas[num]
    }

hexagramas_dict = {}
for i in range(1, 65):
    hexagramas_dict[i] = gerar_hexagrama(i)

# Gerar arquivo JS limpo
js_content = "/**\n * hexagramas.js — Base de dados completa dos 64 Hexagramas do I Ching\n * Textos autorais e originais por Arthur Camargo (CRTH-BR 17948)\n */\n\nconst HEXAGRAMAS = " + json.dumps(hexagramas_dict, ensure_ascii=False, indent=2) + ";\n"

with open('/home/arthur/Downloads/Antigravity/arthur_camargo_landingpage/oraculo/hexagramas.js', 'w', encoding='utf-8') as f:
    f.write(js_content)

print("Arquivo hexagramas.js atualizado com sucesso com 64 Hexagramas autorais!")
